# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-09 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=20, unique=True)),
                ('api_key', models.CharField(max_length=20, unique=True)),
                ('secret_key', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '客户数据表',
                'db_table': 'client_info',
            },
        ),
    ]
