# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-09 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JieCardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField(unique=True)),
                ('digest', models.CharField(max_length=2000)),
                ('key_digest', models.CharField(blank=True, max_length=500)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='apps.recall_jcd.ClientInfo')),
            ],
            options={
                'verbose_name_plural': '杰卡德数据表',
                'db_table': 'jie_card_data',
            },
        ),
    ]
