# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-10 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiecarddata',
            name='indexer',
            field=models.CharField(choices=[('1', '完成'), ('0', '未完成')], default='0', max_length=4),
        ),
    ]
