# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-11 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0003_remove_jiecarddata_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='user_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
