# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-12 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0005_moviecfdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='user_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
