# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0006_clientinfo_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordKeyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField()),
                ('key_digest', models.CharField(blank=True, max_length=3000)),
                ('uc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uc_id', to='recall.ClientInfo')),
            ],
            options={
                'verbose_name_plural': '文章关键字提取',
                'db_table': 'word_key_data',
            },
        ),
    ]
